platform :ios, '10.0'

target 'PhotoManager' do

  use_frameworks!

  # Pods for PhotoManager

pod 'RealmSwift'
pod 'ChartsRealm'
pod 'PinterestLayout'
pod 'SDWebImage'
pod 'ReachabilitySwift', '~> 3.0.0'

end
